version: '3'
services:
  apertis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    # Add environment variables to help with Python module path
    environment:
      - PYTHONPATH=/app
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860" , "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
