version: '3.8' # Updated to a version that robustly supports deploy.resources
services:
  apertis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    # Add environment variables to help with Python module path
    environment:
      - PYTHONPATH=/app
      # Add NVIDIA runtime environment variables if needed by flash-attn or torch
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # Request 1 GPU, can be 'all' or a specific count
              capabilities: [gpu]
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860" , "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
